### ISSUE TITLE
Incompatible with MongoDB 3.0

### ISSUE THREAD

**Issue by bswatson** [pa11y/webservice#5]
There appears to be an issue when trying to use pa11y-webservice with the latest version of MongoDB (3.0).  After rolling back to MongoDB v2.6, this issue cleared up and we were able to run pa11y without problems.

```
[user@pa11y pa11y-dashboard]# grunt start-test
Running "nodemon:test" (nodemon) task
8 Jun 20:38:05 - [nodemon] v0.7.10
8 Jun 20:38:05 - [nodemon] to restart at any time, enter `rs`
8 Jun 20:38:05 - [nodemon] watching: /user/repo/pa11y-dashboard
8 Jun 20:38:05 - [nodemon] starting `node index.js`

pa11y-dashboard started
mode: test
uri:  http://0.0.0.0:4000

pa11y-webservice started
mode: test
uri:  http://0.0.0.0:3000

/user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/connection/base.js:242
        throw message;      
              ^
TypeError: undefined is not a function
    at __executeInsertCommand (/user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/db.js:1930:5)
    at /user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/db.js:1442:27
    at /user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/db.js:1560:7
    at /user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/cursor.js:162:16
    at commandHandler (/user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/cursor.js:706:16)
    at /user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/db.js:1806:9
    at Server.Base._callHandler (/user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    at /user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    at MongoReply.parseBody (/user/repo/pa11y-dashboard/node_modules/pa11y-webservice/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
8 Jun 20:38:06 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by azizur** [comment]
Same issue here

**Comment by rowanmanning** [comment]
Hi, I'll look into this ASAP. It might be that the dependencies in pa11y-webservice just need updating, it's quite an old version of mongo-client if I remember rightly.

**Comment by hollsk** [comment]
I can run ok with MongoDB 3.2.4. There have been changes to the webservice dependencies since this was raised, so perhaps the issue has since been resolved, if anybody would like to confirm!

**Comment by rowanmanning** [comment]
@hollsk: if it's working now then we can maybe close the issue. It is likely that a dependency update fixed it. @bswatson, @azizur: are you still having this problem? I'm happy to reopen the issue if you are and investigate properly :)
